### ISSUE TITLE
Jumpy stopped working on Big Sur b2

### ISSUE THREAD

**Issue by michaello** [eddiekaiger/Jumpy#2]
Hello Eddie,
Thank you for this lovely extension, with it I'm working x10 faster! Wish I could buy you a beer or something.
I've installed b2 on my mac and Jumpy stopped working! It's still visible here:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/4096232/87402722-3f9d0500-c5bc-11ea-802a-4dfe0886f8ed.png">

But in Console, after I have re-enabled it it says:
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/4096232/87402806-5e030080-c5bc-11ea-8079-89b5bb64d38b.png">

Any ideas?
Thank you!

**Comment by eddiekaiger** [comment]
Ooh thanks for the heads up, I'll take a look! And glad you're enjoying it 😄

**Comment by michaello** [comment]
Enjoying it is an understatement; my whole workflow relies on this extension.

Extra info: I only have Xcode-beta, not Xcode. 
Trace from pluginkit:
```
pluginkit -m -p com.apple.dt.Xcode.extension.source-editor
+    com.eddiekaiger.Jumpy.JumpyExtension(1.0)
```

**Comment by michaello** [comment]
Hey Eddie,

Great news! I have found the solution. You have to embed XcodeKit for JumpyExtension to make it work on big sur with Xcode 12:
<img width="968" alt="image" src="https://user-images.githubusercontent.com/4096232/88212584-c6ef1600-cc57-11ea-9245-f33ea65ddb54.png">

**Comment by eddiekaiger** [comment]
Oh interesting, thanks for the discovery! I'll update soon

**Comment by michaello** [comment]
Not sure if this is needed, might get fixed in upcoming betas!

**Comment by michaello** [comment]
Related: https://github.com/nicklockwood/SwiftFormat/pull/669

**Comment by hyperphonic0** [comment]
> Not sure if this is needed, might get fixed in upcoming betas!

Its not a bug, its a feature!

Apparently, on macOS 11 extensions have to be built with Xcode 12 and have the XcodeKit.framework embedded. It is a security thing, they say.

**Comment by michaello** [comment]
@hyperphonic0 hmmm, interesting! No recommendations to add it manually so far, so it's not official yet?

**Comment by hyperphonic0** [comment]
Any documentation from Apple on this would be welcome!  I don't know what the 'new security features' in macOS 11 are, but we do know from the Xcode Release Notes that embedding XcodeKit.framework will be needed.

It is mentioned twice, once as an issue with the existing templates, and once in the deprecations section. From the release notes:

### Source Editor

**Known Issues**
A new Xcode Source Editor Extension target doesn’t automatically set up embedding XcodeKit.framework in the extension. (59274389)
_Workaround_: Embed XcodeKit.framework in the extension manually.

An Xcode extension may cause Xcode to hang on launch, or upon enabling the extension. (61952790)
_Workaround_: Disable the Xcode extension in the Extensions pane in System Preferences.

**Deprecations**
For compatibility with new security features in macOS 11, Xcode extensions must be built using Xcode 12 and must embed XcodeKit.framework. An Xcode extension rebuilt with these tools remains compatible with older versions of Xcode and macOS. (51822755)
